### ISSUE TITLE
Would be great to have call to set a folder structure for different types of code

### ISSUE THREAD

**Issue by evshvarov** [doublefint/all.udl#1]
E.g. this folder structure:
src/
     cls/ - classes
     mac/ - mac routines
     inc/ - include files
     dfi/ - dfi files
     int/ - int files

**Comment by doublefint** [comment]
Use sc.all.sub.cls for this purpose:
Import ( copy/past ) classes sc.all.cls and sc.all.sub.cls into your namespace ( but, may be, in different db )
```
NS> s ^%SYS("SourceControlClass", $namespace)="sc.all.sub"
NS> w ##class(sc.all.sub).workdir("path/to/your/workdir")
NS> d ##class(sc.all.sub).export()
```
